### ISSUE TITLE
Joining forces on dwdweather2

### ISSUE THREAD

**Issue by amotl** [JohannesRol/dwdopendata#1]
Dear Johannes,

we recently took over development from [1] and moved to [2], see also [3,4] for more background information about that.

As we also just found your repository, we humbly ask you if you would like to join us in improving the canonical module authored by @marians together?

Because we liked two of the essential ideas you covered with your implementation so much, we already outlined them by [5] and [6] and hope you don't mind or even like that.

We will be happy to hear back from you.

With kind regards,
Andreas.

[1] https://github.com/marians/dwd-weather
[2] https://github.com/hiveeyes/dwdweather2
[3] https://github.com/marians/dwd-weather/issues/3
[4] https://github.com/marians/dwd-weather/issues/8
[5] https://github.com/hiveeyes/dwdweather2/issues/3
[6] https://github.com/hiveeyes/dwdweather2/issues/4

**Comment by JohannesRol** [comment]
Hi Andreas,
thanks for the commondation. I'm new to python, the DWDopendata project is a kind of a exercise for me to learn python.
I could imagine to join at a later point of being, when my python skills are bit better :)
Feel free to use the snippets of my code that you need.

best regards joh

**Comment by amotl** [comment]
Hi Johannes,

thanks for your feedback and happy to hear that you are starting to learn Python. While I do see your point, please don't hesitate to follow the dwdweather2 repository if you still find it interesting what is happening there and where you might be able to contribute by other means than just code. Actually just **reading** others code was probably the best path to learn for myself and I still enjoy it, especially when transitioning to Python3 these days.

In the meanwhile, I wish you good luck and fun improving your Python skills and want to thank you for the ideas (with code!) you have implemented with your approach to consuming data from DWD already - and thanks for your openness to reuse them.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Johannes,

[Wetterdienst](https://github.com/earthobservations/wetterdienst) will be the official successor library for [dwdweather2](https://github.com/panodata/dwdweather2). For more information, see https://github.com/earthobservations/wetterdienst/issues/50. We will be happy if you would join us there.

With kind regards,
Andreas.

cc @gutzbenj
